### PR TITLE
Fix radio button group demos

### LINKED ISSUE #110: Improve vaadin-radio-button-flow demos

### PR DESCRIPTION
**Pull request by shadikhani**
Fix #110

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/114)

### CODE REVIEW

File: vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java [hunk 1]
```diff
@@ -0,0 +1,356 @@
...
+        RadioButtonGroup<String> group = new RadioButtonGroup<>();
+
+        // Note that setting items clear any components
+        group.add(new Label("Foo group"), getFullSizeHr());
+
+        group.setItems("foo", "bar", "baz");
+        group.addComponents("foo", new Label("Not foo selections"),
+                getFullSizeHr());
+
+        group.getElement().getStyle().set("display", "flex");
```
Comment (tomivirkki) [inline vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java]: The demos shouldn't need to use element-level style tweaks.

Comment (shadikhani) [reply vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java]: These are the old demos. I just moved them to the 'tests' part. Should I change it?

Comment (tomivirkki) [reply vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java]: Yes, the demos should not have this kind of hacks

Comment (tomivirkki) [reply vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java]: Ah, didn't understand the "tests" part correctly. So they're just moved from demos as integration tests and the new demos no longer use this code. Although it's weird to have this code in tests as well, it's not that important to fix anymore.

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java [hunk 2]
```diff
@@ -15,330 +15,287 @@
...
+        disabledRadioGroup.getStyle().set("margin-right", "7.5em");
+        VerticalLayout verticalLayout = new VerticalLayout(disabledRadioGroup,
+                radioGroup);
+        addCard("Disabled state", verticalLayout);
     }
 
-    private void addItemRenderer() {
-        Div message = new Div();
-
+    private void readonlyRadioButton() {
```
Comment (tomivirkki) [inline vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: As the component doesn't have a proper readonly mode yet, we could hide this demo for now

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java [hunk 3]
```diff
@@ -15,330 +15,287 @@
...
-        message.setId("button-group-gen-value");
+    private List<Department> getDepartments() {
 
-        addCard("Radio button group with label generator", group, message);
+        DepartmentData departmentData = new DepartmentData();
+        return departmentData.getDepartments();
     }
 
-    private void addItemIconGenerator() {
+    private void entityList() {
```
Comment (tomivirkki) [inline vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Let's move this as the second demo (right after the basic usage demo) since this is more of a realistic use-case

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java [hunk 4]
```diff
@@ -15,330 +15,287 @@
...
-            image.getStyle().set("float", "left");
-            image.getStyle().set("marginRight", "5px");
-            image.getStyle().set("marginTop", "2px");
-            return image;
-        }, Person::getName));
+        // source-example-heading: Entity list
+        RadioButtonGroup<Department> radioGroup = new RadioButtonGroup<>();
+        radioGroup.setLabel("Department");
+        List<Department> departmentList = getDepartments();
+        radioGroup.setItems(departmentList);
```
Comment (tomivirkki) [inline vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: The demo should explicitly set the visual representation of a Department. I believe it's currently relying on the entity's `toString()` which isn't really a best practice. Add something like `radioGroup.setRenderer(new TextRenderer<>(Department::getName));`

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java [hunk 5]
```diff
@@ -15,330 +15,287 @@
...
-        NativeButton button = new NativeButton("Switch read-only state",
-                event -> group.setReadOnly(!group.isReadOnly()));
-        group.addValueChangeListener(
-                event -> valueInfo.setText(group.getValue()));
+        // source-example-heading: Required
+        Employee employee = new Employee();
+        Binder<Employee> binder = new Binder<>();
+
+        RadioButtonGroup<String> radioGroup = new RadioButtonGroup<>();
+        radioGroup.setLabel("Department");
```
Comment (tomivirkki) [inline vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Looking at the demo source, "Department" isn't the property being selected here. Should be changed to "Employee title" or just "Title"

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java [hunk 6]
```diff
@@ -15,330 +15,287 @@
...
         // begin-source-example
-        // source-example-heading: Radio button group with item enabled provider
-        RadioButtonGroup<String> group = new RadioButtonGroup<>();
-        group.setItems("foo", "bar", "baz");
-        group.setItemEnabledProvider(item -> !"bar".equals(item));
+        // source-example-heading: Customizing radio button label
+        RadioButtonGroup<Information> radioButton = new RadioButtonGroup<>();
+        radioButton.setLabel("User");
+        radioButton.setItems(
+                new Information("Gabriella",
```
Comment (tomivirkki) [inline vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: "Information" class used here seems to wrap the name and an image of a person. One of the other demos used "Employee" class, which also represents a person, so it would make sense to combine the properties from "Information" to "Employee" and use the same "Employee" class in both demos.

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java [hunk 7]
```diff
@@ -15,330 +15,287 @@
...
+        radioButton.setRenderer(new ComponentRenderer<>(information -> {
+            Div text = new Div();
+            text.setText(information.getText());
+
+            Image image = new Image();
+            image.setWidth("21px");
+            image.setHeight("21px");
+            image.setSrc(information.getImage());
+
+            FlexLayout wrapper = new FlexLayout();
```
Comment (tomivirkki) [inline vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Wouldn't a horizontal layout with spacing work here? It's a higher-level abstraction so it's more convenient for a demo.

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java (hunk 3 above)
Comment (shadikhani) [reply vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Done.

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java (hunk 4 above)
Comment (shadikhani) [reply vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Done.

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java (hunk 5 above)
Comment (shadikhani) [reply vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Done.

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java (hunk 6 above)
Comment (shadikhani) [reply vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Done.

File: vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java (hunk 7 above)
Comment (shadikhani) [reply vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java]: Didn't change it because it looks ugly with HorizontalLayout.
